import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import Layouts from "@/common/components/layouts/Layouts";
import { ThemeProvider } from "@/providers/ThemeProvider";
import Background from "@/common/components/layouts/background/Background";
import TopLoader from "@/common/components/elements/TopLoader";

const fontOnest = Onest({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={` ${fontOnest.className} antialiased`}>
        <TopLoader />

        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Background />
          <Layouts>{children}</Layouts>
        </ThemeProvider>
      </body>
    </html>
  );
}
