import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import Layouts from "@/common/components/layouts/Layouts";
import { ThemeProvider } from "@/providers/ThemeProvider";
import Background from "@/common/components/layouts/background/Background";
import NextTopLoader from "nextjs-toploader";

const fontOnest = Onest({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={` ${fontOnest.className} antialiased`}>
        <NextTopLoader
          color='#ff0000d3'
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing='ease'
          speed={200}
          shadow='0 0 10px #ff00009d,0 0 5px #ff3a3ac6'
        />

        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Background />
          <Layouts>{children}</Layouts>
        </ThemeProvider>
      </body>
    </html>
  );
}
